# Airties website main page testing

from selenium import webdriver
from selenium.webdriver.firefox.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver import ActionChains
from selenium.webdriver.support.wait import WebDriverWait
from time import sleep
import pyfiglet
from xpathList import XpathList

# Configuration
service = Service("./geckodriver.exe")
driver = webdriver.Firefox(service=service)
driver.implicitly_wait(10)
mouseMove = ActionChains(driver)
airtiesLogo = "AIRTIES"
airtiesLogo = pyfiglet.figlet_format(airtiesLogo)
xpathlist = XpathList()

# Functions
def checkPage(urlName="airties"):
    if urlName in driver.current_url:
        print("Reached", str(urlName), "page..")
    else:
        print("Error! can't reach", str(urlName), "page")

def verifyPage(link="link", linkcontent="linkcontent"):
    if link in driver.current_url:
        print("Returned info:", driver.find_element(By.XPATH, linkcontent).text + "..")
    else:
        print("Error! can't reach", link, "page")

def tabName(path="path"):
    text = driver.find_element(By.XPATH, path).text
    print("Tab name is", text + "..")

def tabChanger(linkName="airties"):                           
    for i in driver.window_handles:              
        driver.switch_to.window(i)          
        if linkName.lower() in driver.current_url.lower(): 
            break 
        
# Test Codes
print(airtiesLogo)                                                                                             
print("Airties website test is starting..")
driver.get("https://airties.com/")
checkPage()
driver.maximize_window()
print("---------Logo & Contact Us Button Test-----------")
driver.find_element(By.XPATH, xpathlist.logo).click()
sleep(2)
logoCheck = driver.current_url
assert "https://airties.com/" == logoCheck
driver.find_element(By.XPATH, xpathlist.contactUs).click()
verifyPage("contact-us", xpathlist.contactUs_Text)
driver.back()
checkPage()
sleep(2)
print("------Linkedin Twitter Youtube Link Test------")
driver.find_element(By.XPATH, xpathlist.linkedin).click()
sleep(2)
tabChanger("linkedin")
checkPage("linkedin")
driver.close()
sleep(2)
tabChanger()
driver.find_element(By.XPATH, xpathlist.twitter).click()
sleep(2)
tabChanger("twitter")
checkPage("twitter")
driver.close()
tabChanger()
driver.find_element(By.XPATH, xpathlist.youtube).click()
sleep(2)
tabChanger("youtube")
checkPage("youtube")
driver.close()
tabChanger()
print("---------Top First Tab Test-----------")
mouseMove.move_to_element(driver.find_element(By.XPATH, xpathlist.tab1)).perform()
tabName(xpathlist.tab1)
driver.find_element(By.XPATH, xpathlist.tab1_0).click()
verifyPage("premium-subscriber", xpathlist.tab1_Text)
driver.back()
checkPage()
sleep(2)
mouseMove.move_to_element(driver.find_element(By.XPATH, xpathlist.tab1)).perform()
tabName(xpathlist.tab1)
driver.find_element(By.XPATH, xpathlist.tab1_1).click()
verifyPage("home-network-usage", xpathlist.tab1_Text)
driver.back()
checkPage()
sleep(2)
mouseMove.move_to_element(driver.find_element(By.XPATH, xpathlist.tab1)).perform()
tabName(xpathlist.tab1)
driver.find_element(By.XPATH, xpathlist.tab1_2).click()
verifyPage("customer-care-diagnostics", xpathlist.tab1_Text)
driver.back()
checkPage()
sleep(2)
mouseMove.move_to_element(driver.find_element(By.XPATH, xpathlist.tab1)).perform()
tabName(xpathlist.tab1)
driver.find_element(By.XPATH, xpathlist.tab1_3).click()
verifyPage("homeowner-self-care", xpathlist.tab1_Text)
print(str(driver.find_element(By.XPATH, xpathlist.tab1).text), "tab test finished")
driver.back()
checkPage()
sleep(2)
print("---------Top Second Tab Test----------")
mouseMove.move_to_element(driver.find_element(By.XPATH, xpathlist.tab2)).perform()
tabName(xpathlist.tab2)
driver.find_element(By.XPATH, xpathlist.tab2_0).click()
verifyPage("airties-edge-software", xpathlist.tab2_Text)
driver.back()
checkPage()
sleep(2)
mouseMove.move_to_element(driver.find_element(By.XPATH, xpathlist.tab2)).perform()
tabName(xpathlist.tab2)
driver.find_element(By.XPATH, xpathlist.tab2_1).click()
verifyPage("airties-access-cpe", xpathlist.tab2_Text)
driver.back()
checkPage()
sleep(2)
mouseMove.move_to_element(driver.find_element(By.XPATH, xpathlist.tab2)).perform()
tabName(xpathlist.tab2)
driver.find_element(By.XPATH, xpathlist.tab2_2).click()
verifyPage("airties-cloud-platform", xpathlist.tab2_Text)
driver.back()
checkPage()
sleep(2)
mouseMove.move_to_element(driver.find_element(By.XPATH, xpathlist.tab2)).perform()
tabName(xpathlist.tab2)
driver.find_element(By.XPATH, xpathlist.tab2_3).click()
verifyPage("vision-companion-app", xpathlist.tab2_Text)
driver.back()
checkPage()
sleep(2)
mouseMove.move_to_element(driver.find_element(By.XPATH, xpathlist.tab2)).perform()
tabName(xpathlist.tab2)
driver.find_element(By.XPATH, xpathlist.tab2_4).click()
verifyPage("wi-fi-professional-services", xpathlist.tab2_Text)
driver.back()
checkPage()
sleep(2)
print("---------Top Third Tab Test----------")
mouseMove.move_to_element(driver.find_element(By.XPATH, xpathlist.tab3)).perform()
tabName(xpathlist.tab3)
driver.find_element(By.XPATH, xpathlist.tab3_0).click()
verifyPage("who-we-are", xpathlist.tab3_Text)
driver.back()
checkPage()
sleep(2)
mouseMove.move_to_element(driver.find_element(By.XPATH, xpathlist.tab3)).perform()
tabName(xpathlist.tab3)
driver.find_element(By.XPATH, xpathlist.tab3_1).click()
verifyPage("careers", xpathlist.tab3_1_Text)
driver.back()
checkPage()
sleep(2)
print("---------Top Fourth Tab Test----------")
mouseMove.move_to_element(driver.find_element(By.XPATH, xpathlist.tab4)).perform()
tabName(xpathlist.tab4)
driver.find_element(By.XPATH, xpathlist.tab4).click()
verifyPage("newsroom", xpathlist.tab4_Text)
driver.back()
checkPage()
sleep(2)
print("---------Middle Bar Button Test----------")
driver.find_element(By.XPATH, xpathlist.middleBar).click()
sleep(2)
tabChanger("insights")
checkPage("insights")
driver.close()
tabChanger()
checkPage()
sleep(2)
print("--------Second Middle Bar Button Test--------")
driver.find_element(By.XPATH, xpathlist.secondMiddleBar1).click()
checkPage("premium-subscriber-wi-fi")
driver.back()
checkPage()
sleep(2)
driver.find_element(By.XPATH, xpathlist.secondMiddleBar2).click()
checkPage("customer-care-diagnostics")
driver.back()
checkPage()
sleep(2)
driver.find_element(By.XPATH, xpathlist.secondMiddleBar3).click()
checkPage("airties-edge-software")
driver.back()
checkPage()
sleep(3)
print("Test Done!")
driver.quit()