
class XpathList:

    logo = "//div[@class='row justify-content-between align-items-top']/div/a/img"
    contactUs = "//div[@class='col-auto d-none d-lg-block']/a"
    contactUs_Text = "//div[@class='breadcrumbs ']//span"
    tab1 = "//div[@class='header header--main row']//ul[@class='menu-primary-menu-container d-md-flex d-block justify-content-between align-items-center']/li[1]/a"
    tab1_0 = "//div[@class='container-fluid d-none d-lg-block']//ul[@id='menu-52']/li[1]/a"
    tab1_1 = "//div[@class='container-fluid d-none d-lg-block']//ul[@id='menu-52']/li[2]/a"
    tab1_2 = "//div[@class='container-fluid d-none d-lg-block']//ul[@id='menu-52']/li[3]/a"
    tab1_3 = "//div[@class='container-fluid d-none d-lg-block']//ul[@id='menu-52']/li[4]/a"
    tab1_Text = "//div[@class='container-fluid block d-none d-md-block']//div[@class='container d-flex align-items-center'][1]//h1[@class='text-white']"
    tab2 = "//div[@class='header header--main row']//ul[@class='menu-primary-menu-container d-md-flex d-block justify-content-between align-items-center']/li[2]/a"
    tab2_0 = "//div[@class='container-fluid d-none d-lg-block']//ul[@id='menu-518']/li[1]/a"
    tab2_1 = "//div[@class='container-fluid d-none d-lg-block']//ul[@id='menu-518']/li[2]/a"
    tab2_2 = "//div[@class='container-fluid d-none d-lg-block']//ul[@id='menu-518']/li[3]/a"
    tab2_3 = "//div[@class='container-fluid d-none d-lg-block']//ul[@id='menu-518']/li[4]/a"
    tab2_4 = "//div[@class='container-fluid d-none d-lg-block']//ul[@id='menu-518']/li[5]/a"
    tab2_Text = "//div[@class='container-fluid block d-none d-md-block']//h1[@class='text-white']"
    tab3 = "//div[@class='header header--main row']//ul[@class='menu-primary-menu-container d-md-flex d-block justify-content-between align-items-center']/li[3]/a"
    tab3_0 = "//div[@class='container-fluid d-none d-lg-block']//ul[@id='menu-517']/li[1]/a"
    tab3_1 = "//div[@class='container-fluid d-none d-lg-block']//ul[@id='menu-517']/li[2]/a"
    tab3_1_Text = "//div[@class='container d-flex align-items-center']//h1[@class='text-white']"
    tab3_Text = "//div[@class='container d-flex align-items-center']//h1[@class='text-black']"
    tab4 = "//div[@class='header header--main row']//ul[@class='menu-primary-menu-container d-md-flex d-block justify-content-between align-items-center']/li[4]/a"
    tab4_Text = "//div[@class='row block--header bg-white']//h1[@class='text-black']"
    linkedin = "//div[@class='header--tale__right col-auto']//div[@class='icon-linkedin']/a"
    twitter = "//div[@class='header--tale__right col-auto']//div[@class='icon-twitter']/a"
    youtube = "//div[@class='header--tale__right col-auto']//div[@class='icon-youtube']/a"
    middleBar = "//div[@class='row d-none d-md-flex']//a"
    secondMiddleBar1 = "//p[@class='font-weight-bold text-black-anchor-child b-anchor-child']//a[text()='Deliver high ']"
    secondMiddleBar2 = "//p[@class='font-weight-bold text-black-anchor-child b-anchor-child']//a[text()='Manage the Connected ']"
    secondMiddleBar3 = "//p[@class='font-weight-bold text-black-anchor-child b-anchor-child']//a[text()=' Easily deploy ']"
    